version: "3"
services:
  app:
    depends_on:
      - db
    restart: always
    build: .
    ports:
      - "8000:3000"
    environment:
      - DATABASE_HOST=db
      - APP_HOST=0.0.0.0
      
  db:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodata: 
